# Generated by Django 4.0.4 on 2022-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256)),
                ('lname', models.CharField(max_length=256)),
                ('hemail', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=256)),
                ('pswd', models.CharField(max_length=256)),
                ('mobno', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='das',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=256)),
                ('epass', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256)),
                ('price', models.IntegerField(null=True)),
                ('desc', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=256)),
                ('upass', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=256)),
                ('lname', models.CharField(max_length=256)),
                ('iemail', models.EmailField(max_length=254)),
                ('icon', models.CharField(max_length=256)),
                ('rtpye', models.CharField(max_length=256, null=True)),
                ('rno', models.PositiveIntegerField()),
                ('eid', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=256)),
                ('hemail', models.EmailField(max_length=254)),
                ('ename', models.CharField(max_length=256)),
                ('eloc', models.CharField(max_length=256)),
                ('edesc', models.TextField()),
                ('pswd', models.CharField(max_length=256)),
                ('sdate', models.DateField()),
                ('stime', models.TimeField()),
                ('edate', models.DateField()),
                ('etime', models.TimeField()),
                ('rdate', models.DateField()),
                ('rtime', models.TimeField()),
            ],
        ),
    ]
